"""Generate a secret-free local demo reset and recovery guide."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DEFAULT_OUTPUT = Path("var/review-packets/v3/operator-workbench/DEMO_RESET_GUIDE.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]


class DemoResetGuideError(RuntimeError):
    """Raised when demo reset guidance cannot be generated safely."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    try:
        report = build_guide(repo_root=Path.cwd().resolve(), output=args.output)
    except DemoResetGuideError as exc:
        print(f"demo reset guide failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print("Ithildin demo reset guide")
        print(f"valid: {str(report['valid']).lower()}")
        print(f"output: {report['output']}")
    return 0 if report["valid"] else 1


def build_guide(*, repo_root: Path, output: Path) -> dict[str, Any]:
    _require_project_root(repo_root)
    commit = _git(repo_root, ["rev-parse", "HEAD"])
    dirty = bool(_git(repo_root, ["status", "--short"]))
    report = {
        "schema_version": "1",
        "valid": True,
        "generated_at": datetime.now(UTC).isoformat(),
        "commit": commit,
        "dirty": dirty,
        "output": output.as_posix(),
        "reset_commands": [
            "make compose-down",
            "make demo-seed",
            "make demo-state-report",
            "make demo-readiness-summary",
            "make demo-workbench",
        ],
        "manual_checks": [
            "inspect DEMO_FLOW_RESULT.md if make demo-flow completed",
            "inspect Agent Runs in the review console",
            "export run evidence for the selected run",
            "verify audit status in System Trust",
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_guide(report), encoding="utf-8")
    return report


def render_guide(report: dict[str, Any]) -> str:
    lines = [
        "# Demo Reset Guide",
        "",
        "Generated by `make demo-reset-guide`. This guide is read-only guidance for",
        "returning the local demo to a known state. It does not delete databases, repair",
        "patch diagnostics, approve actions, call governed tools, start services, stop",
        "services, or manage sandbox/container lifecycle.",
        "",
        "## Status",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- commit: `{report['commit']}`",
        f"- dirty: `{str(report['dirty']).lower()}`",
        "",
        "## Normal Reset Path",
        "",
        "1. Run `make compose-down` if the local Compose stack was started.",
        "2. Run `make demo-seed` to restore tracked sample files into the ignored demo workspace.",
        "3. Run `make demo-state-report` to inspect seed, API/UI reachability, and next commands.",
        "4. Run `make demo-readiness-summary` to refresh ready/missing/optional/deferred status.",
        "5. Run `make demo-workbench` to refresh packet evidence after the reset.",
        "",
        "## If Demo Flow Stopped Early",
        "",
        "- If no approval was created, reseed with `make demo-seed` and retry only after",
        "  checking the error.",
        "- If an approval was created but not applied, inspect the Approvals panel before",
        "  deciding anything.",
        "- If patch apply completed, inspect `DEMO_FLOW_RESULT.md`, Agent Runs, audit",
        "  verification, and Export Run Evidence.",
        "- If patch diagnostics report recovery required, do not rerun blindly; inspect",
        "  `GET /patch-apply-diagnostics` first.",
        "",
        "## Evidence To Refresh",
        "",
        "- `var/review-packets/v3/operator-workbench/DEMO_FLOW_RESULT.md` after `make demo-flow`.",
        "- `var/review-packets/v3/operator-workbench/DEMO_STATE_REPORT.md` after",
        "  `make demo-state-report`.",
        "- `var/review-packets/v3/operator-workbench/DEMO_READINESS_SUMMARY.md` after",
        "  `make demo-readiness-summary`.",
        "- `var/review-packets/v3/operator-workbench/WORKBENCH_DEMO_INDEX.md` after",
        "  `make demo-workbench`.",
        "",
        "## Boundary",
        "",
        "This guide does not provide automatic repair, rollback, database cleanup, sandbox",
        "control, SIEM custody, compliance automation, production security, or proof of",
        "activity outside Ithildin-mediated actions.",
        "",
    ]
    return "\n".join(lines)


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise DemoResetGuideError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


def _git(repo_root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


if __name__ == "__main__":
    raise SystemExit(main())
