"""Generate a secret-free guided-demo state report."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import demo_readiness_summary, live_demo_status

DEFAULT_OUTPUT = Path("var/review-packets/v3/operator-workbench/DEMO_STATE_REPORT.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
SEEDED_WORKSPACE = Path("workspaces/demo")
SEEDED_README = SEEDED_WORKSPACE / "README.md"


class DemoStateReportError(RuntimeError):
    """Raised when demo state report generation fails."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--skip-probes", action="store_true")
    args = parser.parse_args()
    try:
        report = build_report(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            probe_endpoints=not args.skip_probes,
        )
    except DemoStateReportError as exc:
        print(f"demo state report failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        _print_human(report)
    return 0 if report["valid"] else 1


def build_report(
    *,
    repo_root: Path,
    output: Path,
    probe_endpoints: bool = True,
) -> dict[str, Any]:
    _require_project_root(repo_root)
    with _temporary_output(repo_root, "LIVE_DEMO_INDEX_FOR_STATE.md") as live_output:
        live_status = live_demo_status.build_status(
            repo_root=repo_root,
            output=live_output,
            probe_endpoints=probe_endpoints,
        )
    with _temporary_output(repo_root, "DEMO_READINESS_FOR_STATE.md") as readiness_output:
        readiness = demo_readiness_summary.build_summary(
            repo_root=repo_root,
            output=readiness_output,
            probe_endpoints=probe_endpoints,
        )
    commit = _git(repo_root, ["rev-parse", "HEAD"])
    dirty = bool(_git(repo_root, ["status", "--short"]))
    seeded = _seeded_workspace_status(repo_root)
    report = {
        "schema_version": "1",
        "valid": bool(live_status["valid"] and readiness["valid"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "commit": commit,
        "dirty": dirty,
        "tool_count": readiness.get("tool_count"),
        "seeded_workspace": seeded,
        "api_healthz_reachable": live_status["endpoints"]["api_healthz"]["reachable"],
        "ui_root_reachable": live_status["endpoints"]["ui_root"]["reachable"],
        "compose_available": live_status["compose"]["available"],
        "compose_running_hint": live_status["compose"]["running_hint"],
        "warnings": live_status["preflight"]["warnings"],
        "missing": readiness["missing"],
        "ready": readiness["ready"],
        "artifact_paths": {
            "state_report": output.as_posix(),
            "workbench_packet": readiness["workbench_packet_path"],
            "live_demo_packet": "var/review-packets/v3/live-demo",
            "operator_demo_guide": (
                "var/review-packets/v3/operator-workbench/OPERATOR_DEMO_GUIDE.md"
            ),
            "run_evidence_export": "review console: Export Run Evidence",
        },
        "recommended_next_demo_commands": _next_commands(
            seeded=seeded,
            api_reachable=live_status["endpoints"]["api_healthz"]["reachable"],
            ui_reachable=live_status["endpoints"]["ui_root"]["reachable"],
        ),
        "does_not_do": [
            "start services",
            "stop services",
            "call governed tools",
            "approve actions",
            "mutate governed workspaces",
            "manage sandbox lifecycle",
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_report(report), encoding="utf-8")
    return report


def render_report(report: dict[str, Any]) -> str:
    lines = [
        "# Demo State Report",
        "",
        "Generated by `make demo-state-report`. This report is secret-free and does not",
        "start services, stop services, call governed tools, approve actions, mutate",
        "governed workspaces, or manage sandbox lifecycle.",
        "",
        "## Current State",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- commit: `{report['commit']}`",
        f"- dirty: `{str(report['dirty']).lower()}`",
        f"- tool_count: `{report['tool_count']}`",
        f"- valid: `{str(report['valid']).lower()}`",
        f"- seeded_workspace_exists: `{str(report['seeded_workspace']['exists']).lower()}`",
        f"- seeded_readme_exists: `{str(report['seeded_workspace']['readme_exists']).lower()}`",
        f"- api_healthz_reachable: `{str(report['api_healthz_reachable']).lower()}`",
        f"- ui_root_reachable: `{str(report['ui_root_reachable']).lower()}`",
        f"- compose_available: `{str(report['compose_available']).lower()}`",
        f"- compose_running_hint: `{str(report['compose_running_hint']).lower()}`",
        "",
        "## Ready",
        "",
    ]
    lines.extend(f"- {item}" for item in report["ready"])
    lines.extend(["", "## Missing", ""])
    lines.extend(f"- {item}" for item in report["missing"] or ["none"])
    lines.extend(["", "## Warnings", ""])
    lines.extend(f"- {item}" for item in report["warnings"] or ["none"])
    lines.extend(["", "## Artifact Paths", ""])
    for label, path in report["artifact_paths"].items():
        lines.append(f"- {label}: `{path}`")
    lines.extend(["", "## Recommended Next Demo Commands", ""])
    lines.extend(
        f"{index}. `{command}`"
        for index, command in enumerate(report["recommended_next_demo_commands"], 1)
    )
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This report does not prove OS isolation, SIEM custody, compliance automation,",
            "production security, host compromise resistance, external notarization, or",
            "activity outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


class _temporary_output:
    def __init__(self, repo_root: Path, name: str) -> None:
        self.path = repo_root / "var/review-packets/v3/operator-workbench" / name

    def __enter__(self) -> Path:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        return self.path

    def __exit__(self, *_exc: object) -> None:
        self.path.unlink(missing_ok=True)


def _seeded_workspace_status(repo_root: Path) -> dict[str, Any]:
    root = repo_root / SEEDED_WORKSPACE
    readme = repo_root / SEEDED_README
    return {
        "path": SEEDED_WORKSPACE.as_posix(),
        "exists": root.exists(),
        "readme_exists": readme.exists(),
    }


def _next_commands(*, seeded: dict[str, Any], api_reachable: bool, ui_reachable: bool) -> list[str]:
    commands = ["make live-demo-preflight"]
    if not seeded["exists"] or not seeded["readme_exists"]:
        commands.append("make demo-seed")
    if not api_reachable or not ui_reachable:
        commands.append("make compose-up && make compose-smoke")
    commands.extend(
        [
            "uv run python -m ithildin_mcp_server",
            "make demo-flow",
            "open http://127.0.0.1:5173",
            "Export Run Evidence",
            "make demo-workbench",
            "make compose-down",
        ]
    )
    return commands


def _print_human(report: dict[str, Any]) -> None:
    print("Ithildin demo state report")
    print(f"valid: {str(report['valid']).lower()}")
    print(f"commit: {report['commit']}")
    print(f"dirty: {str(report['dirty']).lower()}")
    print(f"tool_count: {report['tool_count']}")
    print(f"seeded_workspace_exists: {str(report['seeded_workspace']['exists']).lower()}")
    print(f"api_healthz_reachable: {str(report['api_healthz_reachable']).lower()}")
    print(f"ui_root_reachable: {str(report['ui_root_reachable']).lower()}")
    print("next:")
    for command in report["recommended_next_demo_commands"]:
        print(f"- {command}")


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise DemoStateReportError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


def _git(repo_root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


if __name__ == "__main__":
    raise SystemExit(main())
