"""Dry-run external finding intake without changing committed finding records."""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import reviewer_findings

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    report = run_dry_run()
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(render_report(report))
    return 1 if report["failures"] else 0


def run_dry_run() -> dict[str, Any]:
    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="ithildin-ext-finding-dry-run-") as raw_dir:
        findings_dir = Path(raw_dir)
        valid_path = findings_dir / "ext-900-dry-run.md"
        valid_path.write_text(_valid_external_finding(), encoding="utf-8")
        records = reviewer_findings.validate_findings(
            findings_dir=findings_dir,
            repo_root=ROOT,
        )
        if len(records) != 1 or records[0].finding_id != "EXT-900":
            failures.append("valid EXT fixture did not validate as expected")

        invalid_path = findings_dir / "ext-901-open-high.md"
        invalid_path.write_text(_open_high_external_finding(), encoding="utf-8")
        high_open_rejected = False
        try:
            reviewer_findings.validate_findings(
                findings_dir=findings_dir,
                repo_root=ROOT,
            )
        except reviewer_findings.FindingValidationError as exc:
            high_open_rejected = "open high finding" in str(exc)
        else:
            high_open_rejected = False
        if not high_open_rejected:
            failures.append("open high EXT fixture was not rejected")

    return {
        "schema_version": "1",
        "valid": not failures,
        "failures": failures,
        "validated_fixture_id": "EXT-900",
        "open_high_fixture_rejected": high_open_rejected,
        "committed_findings_mutated": False,
    }


def _valid_external_finding() -> str:
    return """# EXT-900 Dry Run Finding

- Finding ID: EXT-900
- Severity: low
- Area: external finding intake dry run
- Affected files/functions: docs/codex/external-review-intake-v2.md
- Claim being tested: external findings can be converted into the shared finding schema
- Observed behavior: dry-run fixture validates without mutating committed finding records
- Risk: dry-run only
- Recommended fix: none
- Blocking status: later
- Disposition: deferred
- Verification notes: dry-run fixture generated by scripts/external_findings_intake_dry_run.py
"""


def _open_high_external_finding() -> str:
    return """# EXT-901 Open High Finding

- Finding ID: EXT-901
- Severity: high
- Area: external finding intake dry run
- Affected files/functions: docs/codex/external-review-intake-v2.md
- Claim being tested: open high external findings fail closed
- Observed behavior: fixture intentionally remains open
- Risk: dry-run should reject this record
- Recommended fix: close, defer, reject, or accept risk before gates pass
- Blocking status: should-fix
- Disposition: open
- Verification notes: dry-run negative fixture
"""


def render_report(report: dict[str, Any]) -> str:
    lines = [
        "Ithildin external findings intake dry run",
        f"valid: {str(report['valid']).lower()}",
        f"validated_fixture_id: {report['validated_fixture_id']}",
        f"open_high_fixture_rejected: {str(report['open_high_fixture_rejected']).lower()}",
        "committed_findings_mutated: false",
    ]
    if report["failures"]:
        lines.append("failures:")
        lines.extend(f"- {failure}" for failure in report["failures"])
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
