"""Run the non-service-starting guided local demo evidence path."""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
DEFAULT_TRANSCRIPT = Path("var/review-packets/v3/guided-demo/GUIDED_DEMO_TRANSCRIPT.md")


@dataclass(frozen=True)
class GuidedStep:
    name: str
    command: list[str]
    description: str


STEPS = [
    GuidedStep(
        "preflight",
        ["make", "live-demo-preflight"],
        "Check local-preview posture before any demo action.",
    ),
    GuidedStep(
        "seed",
        ["make", "demo-seed"],
        "Refresh the ignored demo workspace used by the optional mediated flow.",
    ),
    GuidedStep(
        "state-report",
        ["make", "demo-state-report"],
        "Write the current ready/missing/reachable/artifact report.",
    ),
    GuidedStep(
        "operator-guide",
        ["make", "operator-demo-guide"],
        "Write the preflight-to-cleanup operator walkthrough.",
    ),
    GuidedStep(
        "workbench-smoke",
        ["make", "demo-workbench-smoke"],
        "Write the deterministic readiness transcript.",
    ),
    GuidedStep(
        "workbench-packet",
        [
            "uv",
            "run",
            "python",
            "scripts/workbench_evidence_packet.py",
            "--allow-dirty",
            "--skip-commands",
        ],
        "Refresh the focused operator workbench packet.",
    ),
]


class GuidedDemoError(RuntimeError):
    """Raised when the guided demo path cannot complete."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--transcript", type=Path, default=DEFAULT_TRANSCRIPT)
    parser.add_argument("--skip-commands", action="store_true")
    args = parser.parse_args()
    try:
        results = run_guided_demo(
            repo_root=Path.cwd().resolve(),
            transcript=args.transcript,
            run_commands=not args.skip_commands,
        )
    except GuidedDemoError as exc:
        print(f"guided demo failed: {exc}", file=sys.stderr)
        return 1
    _print_human(results, args.transcript)
    return 0


def run_guided_demo(
    *,
    repo_root: Path,
    transcript: Path,
    run_commands: bool = True,
) -> list[dict[str, object]]:
    _require_project_root(repo_root)
    results = [_run_step(step, repo_root=repo_root, run_commands=run_commands) for step in STEPS]
    failures = [result for result in results if result["returncode"] != 0]
    transcript.parent.mkdir(parents=True, exist_ok=True)
    transcript.write_text(_render_transcript(results, run_commands=run_commands), encoding="utf-8")
    if failures:
        failed = ", ".join(str(result["name"]) for result in failures)
        raise GuidedDemoError(f"guided demo step failed: {failed}")
    return results


def _run_step(
    step: GuidedStep,
    *,
    repo_root: Path,
    run_commands: bool,
) -> dict[str, object]:
    if not run_commands:
        return {
            "name": step.name,
            "command": step.command,
            "description": step.description,
            "returncode": 0,
            "stdout": "command execution skipped for fixture/test transcript generation",
            "stderr": "",
        }
    result = subprocess.run(
        step.command,
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
    )
    return {
        "name": step.name,
        "command": step.command,
        "description": step.description,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def _render_transcript(results: list[dict[str, object]], *, run_commands: bool) -> str:
    lines = [
        "# Guided Demo Transcript",
        "",
        "Generated by `make guided-demo`. The default path does not start Compose, stop",
        "services, call governed tools, approve actions, run browser automation, or manage",
        "sandbox lifecycle. It refreshes local demo evidence and prints the next manual",
        "operator actions.",
        "",
        "## Status",
        "",
        f"- generated_at: `{datetime.now(UTC).isoformat()}`",
        f"- command_execution_enabled: `{str(run_commands).lower()}`",
        "- tool_count_expected: `15`",
        "- new_power_classes_allowed: `false`",
        "",
        "## Steps",
        "",
    ]
    for result in results:
        command = " ".join(result["command"])  # type: ignore[arg-type]
        lines.extend(
            [
                f"### {result['name']}",
                "",
                f"- command: `{command}`",
                f"- description: {result['description']}",
                f"- exit_code: `{result['returncode']}`",
                "",
                "```text",
                str(result["stdout"]).rstrip(),
                "```",
                "",
            ]
        )
        if result["stderr"]:
            lines.extend(["stderr:", "", "```text", str(result["stderr"]).rstrip(), "```", ""])
    lines.extend(
        [
            "## Manual Next Actions",
            "",
            "1. Start local services only when you intend to: "
            "`make compose-up && make compose-smoke`.",
            "2. Launch the local MCP server: `uv run python -m ithildin_mcp_server`.",
            "3. Create the mediated demo run: `make demo-flow`.",
            "4. Open `http://127.0.0.1:5173` and inspect Agent Runs.",
            "5. Download `Export Run Evidence` from the selected run.",
            "6. Clean up local services with `make compose-down` if Compose was started.",
            "",
            "## Boundary",
            "",
            "This transcript does not prove OS isolation, SIEM custody, compliance automation,",
            "production security, host compromise resistance, external notarization, or",
            "activity outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _print_human(results: list[dict[str, object]], transcript: Path) -> None:
    print("Ithildin guided demo")
    print(f"transcript: {transcript}")
    for result in results:
        command = " ".join(result["command"])  # type: ignore[arg-type]
        print(f"- {result['name']}: {command} -> {result['returncode']}")
    print("next:")
    print("- make compose-up && make compose-smoke")
    print("- uv run python -m ithildin_mcp_server")
    print("- make demo-flow")
    print("- open http://127.0.0.1:5173")
    print("- Export Run Evidence")
    print("- make compose-down")


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise GuidedDemoError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


if __name__ == "__main__":
    raise SystemExit(main())
