"""Generate secret-free evidence for the optional Compose smoke path."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import live_demo_status

DEFAULT_OUTPUT = Path("var/review-packets/v3/live-demo/LIVE_DEMO_COMPOSE_SMOKE.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
SMOKE_TIMEOUT_SECONDS = 30
FORBIDDEN_MARKERS = [
    "PRIVATE KEY",
    "BEGIN OPENSSH",
    "ITHILDIN_ADMIN_TOKEN=",
    "dev-admin-token-change-me",
    "Authorization:",
    "Bearer ",
    "diff --git",
    "response body:",
]


class LiveDemoComposeSmokeEvidenceError(RuntimeError):
    """Raised when Compose smoke evidence cannot be generated."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--run-smoke",
        action="store_true",
        help="Run make compose-smoke. By default this records status without running the smoke.",
    )
    args = parser.parse_args()
    try:
        report = build_evidence(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            run_smoke=args.run_smoke,
        )
    except LiveDemoComposeSmokeEvidenceError as exc:
        print(f"live demo compose smoke evidence failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(f"Built live-demo Compose smoke evidence at {args.output}")
        print(f"status: {'pass' if report['valid'] else 'fail'}")
        print(f"smoke_status: {report['smoke']['status']}")
    return 0 if report["valid"] else 1


def build_evidence(*, repo_root: Path, output: Path, run_smoke: bool = False) -> dict[str, Any]:
    _require_project_root(repo_root)
    status = live_demo_status.build_status(
        repo_root=repo_root,
        output=output.parent / "LIVE_DEMO_INDEX.md",
        probe_endpoints=True,
    )
    smoke = _run_smoke(repo_root) if run_smoke else _not_run_smoke()
    report = {
        "valid": bool(status["valid"] and smoke["valid"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "run_smoke": run_smoke,
        "preflight": status["preflight"],
        "compose": {
            "available": status["compose"]["available"],
            "expected_services_present": status["compose"]["expected_services_present"],
            "expected_services_running": status["compose"]["expected_services_running"],
            "expected_service_states": status["compose"]["expected_service_states"],
            "safe_error": status["compose"]["safe_error"],
        },
        "endpoints": status["endpoints"],
        "smoke": smoke,
        "does_not_do": [
            "start services",
            "stop services",
            "pull images",
            "build images",
            "mount Docker sockets",
            "call governed tools directly",
            "read secrets",
            "change host settings",
        ],
    }
    rendered = render_evidence(report)
    _assert_secret_free(rendered)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return report


def render_evidence(report: dict[str, Any]) -> str:
    lines = [
        "# Live Demo Compose Smoke Evidence",
        "",
        "This artifact is generated by `make live-demo-compose-smoke-evidence`. It is",
        "secret-free operator evidence for the optional local Docker Compose demo path.",
        "",
        "By default it does not run `make compose-smoke`; it records the current Compose",
        "service snapshot and localhost endpoint reachability. To intentionally observe",
        "the smoke command after starting the local stack, run:",
        "",
        "```sh",
        "uv run python scripts/live_demo_compose_smoke_evidence.py --run-smoke",
        "```",
        "",
        "## Status",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- run_smoke: `{str(report['run_smoke']).lower()}`",
        f"- valid: `{str(report['valid']).lower()}`",
        f"- tool_count: `{report['preflight']['tool_count']}`",
        f"- loopback_ports_valid: `{str(report['preflight']['loopback_ports_valid']).lower()}`",
        f"- docker_socket_mounted: `{str(report['preflight']['docker_socket_mounted']).lower()}`",
        f"- telemetry_enabled: `{str(report['preflight']['telemetry_enabled']).lower()}`",
        f"- compose_available: `{str(report['compose']['available']).lower()}`",
        "- compose_expected_services_present: "
        f"`{str(report['compose']['expected_services_present']).lower()}`",
        "- compose_expected_services_running: "
        f"`{str(report['compose']['expected_services_running']).lower()}`",
        "- api_healthz_reachable: "
        f"`{str(report['endpoints']['api_healthz']['reachable']).lower()}`",
        f"- ui_root_reachable: `{str(report['endpoints']['ui_root']['reachable']).lower()}`",
        "",
        "## Expected Service States",
        "",
    ]
    for service, state in report["compose"]["expected_service_states"].items():
        lines.append(f"- `{service}`: `{state}`")
    lines.extend(
        [
            "",
            "## Smoke Command",
            "",
            f"- command: `{' '.join(report['smoke']['command'])}`",
            f"- status: `{report['smoke']['status']}`",
            f"- returncode: `{report['smoke']['returncode']}`",
            f"- safe_error: `{report['smoke']['safe_error'] or 'none'}`",
            "",
            "```text",
            str(report["smoke"]["stdout"]).rstrip(),
            "```",
        ]
    )
    if report["smoke"]["stderr"]:
        lines.extend(["", "stderr:", "", "```text", str(report["smoke"]["stderr"]).rstrip(), "```"])
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This evidence does not start services, stop services, pull images, build images,",
            "mount Docker sockets, grant Docker authority to Ithildin, call governed tools",
            "directly, prove OS isolation, prove production deployment safety, or claim",
            "activity outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _run_smoke(repo_root: Path) -> dict[str, Any]:
    command = ["make", "compose-smoke"]
    try:
        result = subprocess.run(
            command,
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=SMOKE_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        return {
            "valid": True,
            "command": command,
            "status": "timeout",
            "returncode": 124,
            "stdout": _bounded(_output_text(exc.stdout)),
            "stderr": "compose smoke timed out",
            "safe_error": "compose smoke timed out",
        }
    status = "passed" if result.returncode == 0 else "failed"
    return {
        "valid": True,
        "command": command,
        "status": status,
        "returncode": result.returncode,
        "stdout": _bounded(result.stdout),
        "stderr": _bounded(result.stderr),
        "safe_error": None if result.returncode == 0 else "compose smoke failed",
    }


def _not_run_smoke() -> dict[str, Any]:
    return {
        "valid": True,
        "command": ["make", "compose-smoke"],
        "status": "not_run",
        "returncode": None,
        "stdout": (
            "compose smoke was not run; start the local stack and pass --run-smoke "
            "to observe it"
        ),
        "stderr": "",
        "safe_error": None,
    }


def _output_text(value: str | bytes | None) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return value


def _bounded(value: str, limit: int = 2000) -> str:
    clean = value.replace("\r", "")
    if len(clean) <= limit:
        return clean
    return clean[:limit] + "\n[truncated]"


def _assert_secret_free(text: str) -> None:
    for marker in FORBIDDEN_MARKERS:
        if marker in text:
            raise LiveDemoComposeSmokeEvidenceError(
                f"evidence contains forbidden marker: {marker}"
            )


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise LiveDemoComposeSmokeEvidenceError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


if __name__ == "__main__":
    raise SystemExit(main())
