"""Build a secret-free live-demo evidence summary."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import live_demo_status

DEFAULT_OUTPUT = Path("var/review-packets/v3/live-demo/LIVE_DEMO_EVIDENCE_SUMMARY.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
ARTIFACTS = {
    "live_demo_status": Path("var/review-packets/v3/live-demo/LIVE_DEMO_INDEX.md"),
    "live_demo_smoke": Path("var/review-packets/v3/live-demo/LIVE_DEMO_SMOKE.md"),
    "signed_evidence_demo_summary": Path(
        "var/review-packets/v0.2/signed-evidence-demo/SIGNED_EVIDENCE_DEMO.md"
    ),
    "signed_evidence_demo_hashes": Path(
        "var/review-packets/v0.2/signed-evidence-demo/signed-evidence-demo-hashes.json"
    ),
    "negative_review_transcripts": Path(
        "var/review-packets/v0.2/negative-review-transcripts/NEGATIVE_REVIEW_TRANSCRIPTS.md"
    ),
    "sandbox_artifact_observed_demo": Path(
        "var/review-packets/v3/sandbox-artifact-observed-demo/SANDBOX_ARTIFACT_OBSERVED_DEMO.md"
    ),
    "hello_world_sandbox_observed_demo": Path(
        "var/review-packets/v3/hello-world-sandbox-observed-demo/"
        "HELLO_WORLD_SANDBOX_OBSERVED_DEMO.md"
    ),
    "hello_world_mission_control_handoff": Path(
        "var/review-packets/v3/hello-world-mission-control-handoff/"
        "HELLO_WORLD_MISSION_CONTROL_HANDOFF.md"
    ),
    "agent_run_correlation_packet": Path("var/review-packets/v3/agent-run-correlation"),
    "operator_sandbox_demo_packet": Path("var/review-packets/v3/operator-sandbox-demo"),
    "consolidated_review_packet": Path(
        "var/review-packets/v0.2/GPT-5.5-Pro-consolidated"
    ),
}
FORBIDDEN_MARKERS = [
    "PRIVATE KEY",
    "BEGIN OPENSSH",
    "ITHILDIN_ADMIN_TOKEN=",
    "dev-admin-token-change-me",
    "diff --git",
    "response body:",
]


class LiveDemoEvidenceSummaryError(RuntimeError):
    """Raised when the live-demo evidence summary cannot be built."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--skip-probes", action="store_true")
    args = parser.parse_args()
    try:
        report = build_summary(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            probe_endpoints=not args.skip_probes,
        )
    except LiveDemoEvidenceSummaryError as exc:
        print(f"live demo evidence summary failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(f"Built live-demo evidence summary at {args.output}")
        print(f"status: {'pass' if report['valid'] else 'fail'}")
    return 0 if report["valid"] else 1


def build_summary(
    *,
    repo_root: Path,
    output: Path,
    probe_endpoints: bool = True,
) -> dict[str, Any]:
    _require_project_root(repo_root)
    status = live_demo_status.build_status(
        repo_root=repo_root,
        output=output.parent / "LIVE_DEMO_INDEX.md",
        probe_endpoints=probe_endpoints,
    )
    artifacts = _artifact_report(repo_root)
    report = {
        "valid": bool(status["valid"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "preflight": status["preflight"],
        "endpoints": status["endpoints"],
        "artifacts": artifacts,
        "does_not_prove": [
            "OS isolation",
            "host compromise resistance",
            "SIEM custody",
            "compliance automation",
            "production security",
            "external notarization",
            "activity outside Ithildin-mediated actions",
        ],
    }
    rendered = render_summary(report)
    _assert_secret_free(rendered)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return report


def render_summary(report: dict[str, Any]) -> str:
    artifacts = report["artifacts"]
    lines = [
        "# Live Demo Evidence Summary",
        "",
        "This summary is generated by `make live-demo-evidence-summary`. It is a read-only,",
        "secret-free index of the current live-demo evidence artifacts.",
        "",
        "## Status Snapshot",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- preflight_valid: `{str(report['preflight']['valid']).lower()}`",
        f"- tool_count: `{report['preflight']['tool_count']}`",
        f"- loopback_ports_valid: `{str(report['preflight']['loopback_ports_valid']).lower()}`",
        f"- docker_socket_mounted: `{str(report['preflight']['docker_socket_mounted']).lower()}`",
        f"- telemetry_enabled: `{str(report['preflight']['telemetry_enabled']).lower()}`",
        "- api_healthz_reachable: "
        f"`{str(report['endpoints']['api_healthz']['reachable']).lower()}`",
        f"- ui_root_reachable: `{str(report['endpoints']['ui_root']['reachable']).lower()}`",
        "",
        "## Evidence Artifacts",
        "",
    ]
    for name, entry in artifacts.items():
        lines.append(
            f"- `{name}`: path=`{entry['path']}` exists=`{str(entry['exists']).lower()}` "
            f"type=`{entry['type']}` sha256=`{entry['sha256'] or 'n/a'}`"
        )
    lines.extend(
        [
            "",
            "## Reviewer Reading Order",
            "",
            "1. `LIVE_DEMO_INDEX.md` for current operator status and artifact paths.",
            "2. `LIVE_DEMO_SMOKE.md` for the generated smoke transcript.",
            "3. `SIGNED_EVIDENCE_DEMO.md` for non-production local signing verification.",
            "4. `NEGATIVE_REVIEW_TRANSCRIPTS.md` for observed safe denials.",
            "5. `SANDBOX_ARTIFACT_OBSERVED_DEMO.md` for observed approval-gated sandbox",
            "   artifact write evidence.",
            "6. `HELLO_WORLD_SANDBOX_OBSERVED_DEMO.md` for the operator-facing Hello",
            "   World version of the observed governed artifact flow.",
            "7. `HELLO_WORLD_MISSION_CONTROL_HANDOFF.md` for the metadata-only",
            "   Mission Control display/import handoff around that observed evidence.",
            "8. Agent Run correlation and operator sandbox demo packets for evidence flow.",
            "9. The consolidated review packet for the broader handoff context.",
            "",
            "## Boundary",
            "",
            "This summary does not include tokens, private keys, raw tool arguments, unified",
            "diffs, file contents, HTTP response bodies, package script values, dependency",
            "names, or raw sensitive paths.",
            "",
            "It does not prove OS isolation, host compromise resistance, SIEM custody,",
            "compliance automation, production security, external notarization, or activity",
            "outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _artifact_report(repo_root: Path) -> dict[str, dict[str, Any]]:
    return {name: _artifact_entry(repo_root, path) for name, path in ARTIFACTS.items()}


def _artifact_entry(repo_root: Path, path: Path) -> dict[str, Any]:
    full_path = repo_root / path
    sha = _digest(full_path) if full_path.is_file() else None
    return {
        "path": path.as_posix(),
        "exists": full_path.exists(),
        "type": "directory" if full_path.is_dir() else "file" if full_path.is_file() else "missing",
        "sha256": sha,
    }


def _digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def _assert_secret_free(text: str) -> None:
    for marker in FORBIDDEN_MARKERS:
        if marker in text:
            raise LiveDemoEvidenceSummaryError(
                f"summary contains forbidden marker: {marker}"
            )


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise LiveDemoEvidenceSummaryError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


if __name__ == "__main__":
    raise SystemExit(main())
