"""Report live-demo status and write a secret-free local demo index."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import live_demo_preflight

DEFAULT_OUTPUT = Path("var/review-packets/v3/live-demo/LIVE_DEMO_INDEX.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
ARTIFACTS = [
    ("live_demo_packet", Path("var/review-packets/v3/live-demo")),
    ("live_demo_smoke", Path("var/review-packets/v3/live-demo/LIVE_DEMO_SMOKE.md")),
    ("operator_sandbox_demo_packet", Path("var/review-packets/v3/operator-sandbox-demo")),
    ("agent_run_correlation_packet", Path("var/review-packets/v3/agent-run-correlation")),
    ("signed_evidence_demo", Path("var/review-packets/v0.2/signed-evidence-demo")),
    (
        "negative_review_transcripts",
        Path("var/review-packets/v0.2/negative-review-transcripts/NEGATIVE_REVIEW_TRANSCRIPTS.md"),
    ),
    (
        "sandbox_artifact_observed_demo",
        Path(
            "var/review-packets/v3/sandbox-artifact-observed-demo/"
            "SANDBOX_ARTIFACT_OBSERVED_DEMO.md"
        ),
    ),
    (
        "hello_world_sandbox_observed_demo",
        Path(
            "var/review-packets/v3/hello-world-sandbox-observed-demo/"
            "HELLO_WORLD_SANDBOX_OBSERVED_DEMO.md"
        ),
    ),
    (
        "hello_world_mission_control_handoff",
        Path(
            "var/review-packets/v3/hello-world-mission-control-handoff/"
            "HELLO_WORLD_MISSION_CONTROL_HANDOFF.md"
        ),
    ),
    (
        "consolidated_review_packet",
        Path("var/review-packets/v0.2/GPT-5.5-Pro-consolidated"),
    ),
]
COMPOSE_STATUS_TIMEOUT_SECONDS = 10


class LiveDemoStatusError(RuntimeError):
    """Raised when live-demo status cannot be built."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--skip-probes", action="store_true")
    args = parser.parse_args()
    try:
        report = build_status(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            probe_endpoints=not args.skip_probes,
        )
    except LiveDemoStatusError as exc:
        print(f"live demo status failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        _print_human(report)
    return 0 if report["valid"] else 1


def build_status(*, repo_root: Path, output: Path, probe_endpoints: bool = True) -> dict[str, Any]:
    _require_project_root(repo_root)
    preflight = live_demo_preflight.build_report(repo_root)
    api_health = _probe_url("http://127.0.0.1:8000/healthz") if probe_endpoints else _skipped()
    ui_health = _probe_url("http://127.0.0.1:5173/") if probe_endpoints else _skipped()
    compose = _compose_status(repo_root)
    artifacts = _artifact_status(repo_root)
    report = {
        "valid": bool(preflight["valid"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "preflight": {
            "valid": preflight["valid"],
            "warnings": preflight["warnings"],
            "failures": preflight["failures"],
            "tool_count": preflight["tool_count"],
            "loopback_ports_valid": preflight["loopback_ports_valid"],
            "docker_socket_mounted": preflight["docker_socket_mounted"],
            "telemetry_enabled": preflight["telemetry_enabled"],
            "http_allowlist_count": preflight["http_allowlist_count"],
        },
        "compose": compose,
        "endpoints": {
            "api_healthz": api_health,
            "ui_root": ui_health,
        },
        "artifacts": artifacts,
        "next_actions": _next_actions(
            preflight=preflight,
            compose=compose,
            api=api_health,
            ui=ui_health,
        ),
        "cleanup_reminder": "run make compose-down after a Compose demo",
        "does_not_do": [
            "start services",
            "stop services",
            "mutate workspaces",
            "call governed tools",
            "read secrets",
            "send network traffic outside localhost probes",
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_index(report), encoding="utf-8")
    return report


def render_index(report: dict[str, Any]) -> str:
    artifacts = report["artifacts"]
    lines = [
        "# Live Demo Operator Index",
        "",
        "This index is generated by `make live-demo-status`. It is secret-free, read-only, and",
        "does not start services, stop services, call governed tools, or mutate workspaces.",
        "",
        "## Current Status",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- preflight_valid: `{str(report['preflight']['valid']).lower()}`",
        f"- tool_count: `{report['preflight']['tool_count']}`",
        f"- loopback_ports_valid: `{str(report['preflight']['loopback_ports_valid']).lower()}`",
        f"- docker_socket_mounted: `{str(report['preflight']['docker_socket_mounted']).lower()}`",
        f"- telemetry_enabled: `{str(report['preflight']['telemetry_enabled']).lower()}`",
        "- api_healthz_reachable: "
        f"`{str(report['endpoints']['api_healthz']['reachable']).lower()}`",
        f"- ui_root_reachable: `{str(report['endpoints']['ui_root']['reachable']).lower()}`",
        "",
        "## Artifact Map",
        "",
    ]
    for name, entry in artifacts.items():
        lines.append(f"- `{name}`: `{entry['path']}` exists=`{str(entry['exists']).lower()}`")
    lines.extend(
        [
            "",
            "## Happy Path",
            "",
            "1. `make live-demo-preflight`",
            "2. `make demo-seed`",
            "3. `make compose-up`",
            "4. `make compose-smoke`",
            "5. open `http://127.0.0.1:5173`",
            "6. `make demo-flow`",
            "7. `make live-demo-status`",
            "8. `make review-candidate`",
            "9. `make compose-down`",
            "",
            "## If Something Fails",
            "",
            "- preflight failure: fix the listed failure before starting services.",
            "- Compose unavailable: run `make live-demo-environment-diagnostics`, use the",
            "  non-Compose evidence commands, and skip local UI/API demo until the local",
            "  Docker/Compose environment is healthy.",
            "- API unreachable: run `make compose-up`, then `make compose-smoke`.",
            "- UI unreachable: confirm the UI service is published on `127.0.0.1:5173`.",
            "- demo-flow failure: keep generated diagnostics and rerun `make live-demo-status`.",
            "- cleanup needed: run `make compose-down`.",
            "",
            "## Boundary",
            "",
            "This status artifact does not prove OS isolation, SIEM custody, compliance",
            "automation,",
            "production security, host compromise resistance, external notarization, or activity",
            "outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise LiveDemoStatusError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


def _probe_url(url: str) -> dict[str, Any]:
    try:
        with urllib.request.urlopen(url, timeout=1) as response:
            status = int(response.status)
    except (OSError, urllib.error.URLError) as exc:
        return {"reachable": False, "status_code": None, "safe_error": type(exc).__name__}
    return {"reachable": 200 <= status < 500, "status_code": status, "safe_error": None}


def _skipped() -> dict[str, Any]:
    return {"reachable": False, "status_code": None, "safe_error": "probe_skipped"}


def _compose_status(repo_root: Path) -> dict[str, Any]:
    env_file = ".env" if (repo_root / ".env").exists() else ".env.example"
    command = [
        "docker",
        "compose",
        "--env-file",
        env_file,
        "-f",
        "deploy/docker-compose.yml",
        "ps",
        "--format",
        "json",
    ]
    try:
        result = subprocess.run(
            command,
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=COMPOSE_STATUS_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return {
            "available": False,
            "running_hint": False,
            "safe_error": "compose status timed out",
        }
    if result.returncode != 0:
        return {
            "available": False,
            "running_hint": False,
            "safe_error": (result.stderr or result.stdout).strip()[:200] or "compose unavailable",
        }
    output = result.stdout.lower()
    return {
        "available": True,
        "running_hint": "ithildin-api" in output and "ithildin-ui" in output,
        "safe_error": None,
    }


def _artifact_status(repo_root: Path) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for name, path in ARTIFACTS:
        full_path = repo_root / path
        result[name] = {
            "path": path.as_posix(),
            "exists": full_path.exists(),
            "is_dir": full_path.is_dir(),
        }
    return result


def _next_actions(
    *,
    preflight: dict[str, Any],
    compose: dict[str, Any],
    api: dict[str, Any],
    ui: dict[str, Any],
) -> list[str]:
    if not preflight["valid"]:
        return ["fix preflight failures before running the live demo"]
    actions = ["run make demo-seed before any demo-flow execution"]
    if not compose["available"] or not compose["running_hint"]:
        actions.append("run make live-demo-environment-diagnostics if Compose is unavailable")
    if not api["reachable"] or not ui["reachable"]:
        actions.append("run make compose-up and make compose-smoke for local API/UI demo")
    actions.extend(
        [
            "run make live-demo-smoke after readiness checks",
            "run make live-demo-packet before handoff",
            "run make compose-down after the Compose demo",
        ]
    )
    return actions


def _print_human(report: dict[str, Any]) -> None:
    print("Ithildin live-demo status")
    print(f"status: {'pass' if report['valid'] else 'fail'}")
    print(f"preflight_valid: {str(report['preflight']['valid']).lower()}")
    print(f"tool_count: {report['preflight']['tool_count']}")
    print(f"compose_available: {str(report['compose']['available']).lower()}")
    print(f"compose_running_hint: {str(report['compose']['running_hint']).lower()}")
    print(f"api_healthz_reachable: {str(report['endpoints']['api_healthz']['reachable']).lower()}")
    print(f"ui_root_reachable: {str(report['endpoints']['ui_root']['reachable']).lower()}")
    print("\nartifacts:")
    for name, entry in report["artifacts"].items():
        print(f"- {name}: {entry['path']} exists={str(entry['exists']).lower()}")
    print("\nnext actions:")
    for action in report["next_actions"]:
        print(f"- {action}")
    print(f"\ncleanup: {report['cleanup_reminder']}")


if __name__ == "__main__":
    raise SystemExit(main())
