"""Generate a secret-free operator demo guide for the local workbench path."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import demo_readiness_summary

DEFAULT_OUTPUT = Path("var/review-packets/v3/operator-workbench/OPERATOR_DEMO_GUIDE.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
STAGES = [
    {
        "name": "Preflight",
        "commands": ["make live-demo-preflight", "make demo-readiness-summary"],
        "operator_result": (
            "local-preview posture and ready/missing/optional/deferred status are visible"
        ),
        "evidence": ["DEMO_READINESS_SUMMARY.md", "LIVE_DEMO_INDEX.md"],
    },
    {
        "name": "Seed",
        "commands": ["make demo-seed"],
        "operator_result": "ignored demo workspace is populated for the optional mediated flow",
        "evidence": ["workspaces/demo/"],
    },
    {
        "name": "Local UI/API",
        "commands": ["make compose-up", "make compose-smoke"],
        "operator_result": "loopback-only local API and review console are reachable",
        "evidence": ["make live-demo-status", "http://127.0.0.1:5173"],
    },
    {
        "name": "Mediated Run",
        "commands": ["uv run python -m ithildin_mcp_server", "make demo-flow"],
        "operator_result": "one local-preview mediated run can be inspected through Agent Runs",
        "evidence": ["Agent Runs panel", "approval evidence", "audit status"],
    },
    {
        "name": "Evidence Export",
        "commands": ["Export Run Evidence", "make demo-workbench"],
        "operator_result": "read-only run evidence and generated packets can be handed off",
        "evidence": ["WORKBENCH_DEMO_INDEX.md", "operator-workbench-artifact-hashes.json"],
    },
    {
        "name": "Cleanup",
        "commands": ["make compose-down"],
        "operator_result": "local Compose services are stopped if they were started",
        "evidence": ["make live-demo-status"],
    },
]


class OperatorDemoGuideError(RuntimeError):
    """Raised when the operator demo guide cannot be generated."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--skip-probes", action="store_true")
    args = parser.parse_args()
    try:
        report = build_guide(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            probe_endpoints=not args.skip_probes,
        )
    except OperatorDemoGuideError as exc:
        print(f"operator demo guide failed: {exc}", file=sys.stderr)
        return 1
    if args.json_output:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        _print_human(report)
    return 0 if report["valid"] else 1


def build_guide(
    *,
    repo_root: Path,
    output: Path,
    probe_endpoints: bool = True,
) -> dict[str, Any]:
    _require_project_root(repo_root)
    readiness_output = output.parent / "DEMO_READINESS_SUMMARY.md"
    readiness = demo_readiness_summary.build_summary(
        repo_root=repo_root,
        output=readiness_output,
        probe_endpoints=probe_endpoints,
    )
    commit = _git(repo_root, ["rev-parse", "HEAD"])
    dirty = bool(_git(repo_root, ["status", "--short"]))
    report = {
        "schema_version": "1",
        "valid": bool(readiness["valid"]),
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "commit": commit,
        "dirty": dirty,
        "tool_count": readiness.get("tool_count"),
        "guide_path": output.as_posix(),
        "readiness_summary_path": readiness_output.as_posix(),
        "stages": STAGES,
        "deferred": readiness["deferred"],
        "does_not_do": readiness["does_not_do"],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_guide(report), encoding="utf-8")
    return report


def render_guide(report: dict[str, Any]) -> str:
    lines = [
        "# Operator Demo Guide",
        "",
        "Generated by `make operator-demo-guide`. This is the plain-language demo path",
        "for a local operator. It is secret-free and does not start services, call",
        "governed tools, approve actions, mutate workspaces, or manage sandbox lifecycle.",
        "",
        "## Status",
        "",
        f"- generated_at: `{report['generated_at']}`",
        f"- commit: `{report['commit']}`",
        f"- dirty: `{str(report['dirty']).lower()}`",
        f"- tool_count: `{report['tool_count']}`",
        f"- valid: `{str(report['valid']).lower()}`",
        f"- readiness_summary_path: `{report['readiness_summary_path']}`",
        "",
        "## Demo Path",
        "",
        "| Stage | Operator Commands | What The Operator Should See | Evidence To Keep |",
        "| --- | --- | --- | --- |",
    ]
    for stage in report["stages"]:
        commands = "<br>".join(f"`{command}`" for command in stage["commands"])
        evidence = "<br>".join(f"`{item}`" for item in stage["evidence"])
        lines.append(
            f"| {stage['name']} | {commands} | {stage['operator_result']} | {evidence} |"
        )
    lines.extend(
        [
            "",
            "## Handoff Reading Order",
            "",
            "1. `WORKBENCH_DEMO_INDEX.md` for the newest packet reading order.",
            "2. `OPERATOR_DEMO_GUIDE.md` for this preflight-to-cleanup walkthrough.",
            "3. `DEMO_READINESS_SUMMARY.md` for ready/missing/optional/deferred status.",
            "4. `WORKBENCH_DEMO_SMOKE.md` for observed readiness commands.",
            "5. `07_WORKBENCH_DEMO_STORY.md` for the narrative artifact.",
            "6. `02_OPERATOR_WORKBENCH_DOCS.md` for evidence contracts.",
            "",
            "## Deferred",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in report["deferred"])
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This guide does not prove OS isolation, SIEM custody, compliance automation,",
            "production security, host compromise resistance, external notarization, or",
            "activity outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _print_human(report: dict[str, Any]) -> None:
    print("Ithildin operator demo guide")
    print(f"valid: {str(report['valid']).lower()}")
    print(f"commit: {report['commit']}")
    print(f"dirty: {str(report['dirty']).lower()}")
    print(f"tool_count: {report['tool_count']}")
    print(f"guide_path: {report['guide_path']}")
    print("demo_path:")
    for stage in report["stages"]:
        print(f"- {stage['name']}: {', '.join(stage['commands'])}")


def _require_project_root(repo_root: Path) -> None:
    missing = [marker.as_posix() for marker in PROJECT_MARKERS if not (repo_root / marker).exists()]
    if missing:
        raise OperatorDemoGuideError(
            "must be run from the Ithildin repo root; missing markers: " + ", ".join(missing)
        )


def _git(repo_root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


if __name__ == "__main__":
    raise SystemExit(main())
