"""Generate a compact ignored v1.0 RC review packet."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import v1_rc_readiness_check

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "var/review-packets/v1.0/rc"
SOURCE_DOCS = [
    ("01_V1_RC_STATUS.md", ROOT / "docs/codex/v1.0-rc-status.md"),
    ("02_V1_OPERATOR_QUICKSTART.md", ROOT / "docs/codex/v1.0-operator-quickstart.md"),
    (
        "02A_V1_OPERATOR_TRIAL_CHECKLIST.md",
        ROOT / "docs/codex/v1.0-operator-trial-checklist.md",
    ),
    (
        "03_V1_WORKBENCH_EVIDENCE_CLOSURE.md",
        ROOT / "docs/codex/v1.0-workbench-evidence-closure.md",
    ),
    ("04_V1_ASSURANCE_CLOSURE.md", ROOT / "docs/codex/v1.0-assurance-closure.md"),
    ("05_V1_RC_FEATURE_FREEZE.md", ROOT / "docs/codex/v1.0-rc-feature-freeze.md"),
    ("06_V1_RC_READINESS_GATE.md", ROOT / "docs/codex/v1.0-rc-readiness-gate.md"),
    ("07_ENTERPRISE_READINESS_RUNWAY.md", ROOT / "docs/codex/enterprise-readiness-runway.md"),
    (
        "08_MISSION_CONTROL_DISPLAY_PROPOSAL.md",
        ROOT / "docs/codex/mission-control-display-integration-proposal.md",
    ),
    (
        "09_MISSION_CONTROL_HANDOFF_SCHEMA.md",
        ROOT / "docs/codex/mission-control-handoff-schema-contract.md",
    ),
    (
        "10_MISSION_CONTROL_NEGATIVE_FIXTURES.md",
        ROOT / "docs/codex/mission-control-handoff-negative-fixtures.md",
    ),
    (
        "11_V1_RC_EXTERNAL_REVIEW_PROMPT.md",
        ROOT / "docs/codex/v1.0-rc-external-review-prompt.md",
    ),
    ("12_V1_RC_FINAL_HANDOFF.md", ROOT / "docs/codex/v1.0-rc-final-handoff.md"),
    (
        "13_V1_RC_POST_REVIEW_TRIAGE.md",
        ROOT / "docs/codex/v1.0-rc-post-review-triage.md",
    ),
]
ARTIFACT_REFERENCES = [
    {
        "path": "var/review-packets/v3/live-demo",
        "purpose": "live-demo smoke, evidence summary, and operator walkthrough packet",
        "proves": "local demo artifacts were regenerated for the current handoff path",
        "does_not_prove": "API/UI services are currently running or production ready",
    },
    {
        "path": "var/review-packets/v3/operator-workbench",
        "purpose": "operator workbench evidence packet",
        "proves": "Agent Run, approval, audit, demo, and workbench evidence are indexed together",
        "does_not_prove": "run control, sandbox orchestration, or SIEM export behavior",
    },
    {
        "path": "var/review-packets/v3/demo-evidence",
        "purpose": "demo evidence closure packet",
        "proves": "demo output, result-check, and evidence contracts are packetized",
        "does_not_prove": "activity outside Ithildin-mediated demo commands",
    },
    {
        "path": "var/review-packets/v3/sandbox-artifact-observed-demo",
        "purpose": "observed bounded sandbox artifact write evidence",
        "proves": (
            "the approval-gated sandbox artifact lane can produce safe local-preview evidence"
        ),
        "does_not_prove": "broad filesystem writes, host promotion, or OS sandbox isolation",
    },
    {
        "path": "var/review-packets/v3/hello-world-sandbox-observed-demo",
        "purpose": "observed Hello World sandbox artifact demo",
        "proves": (
            "the tiny Hello World artifact story can be represented through Ithildin evidence"
        ),
        "does_not_prove": "Mission Control runtime execution or local LLM execution",
    },
    {
        "path": "var/review-packets/v3/hello-world-mission-control-handoff",
        "purpose": "metadata-only Mission Control display/import handoff",
        "proves": "Mission Control can receive labels, hashes, evidence links, and warning state",
        "does_not_prove": "Mission Control execution authority or policy authority",
    },
    {
        "path": "var/review-packets/v3/mission-control-display",
        "purpose": "focused Mission Control display/import review packet",
        "proves": "proposal, schema, negative fixtures, seed handoff, and command evidence align",
        "does_not_prove": "Mission Control runtime importer behavior or authority transfer",
    },
    {
        "path": "docs/codex/sandbox-promotion-evidence-contract.md",
        "purpose": "future trusted-host promotion evidence contract",
        "proves": "promotion states and zone labels are documented as future evidence only",
        "does_not_prove": "trusted-host promotion is implemented or approved",
    },
    {
        "path": "var/review-packets/v0.2/GPT-5.5-Pro-consolidated",
        "purpose": "current consolidated review-candidate handoff folder",
        "proves": "the broad review packet was regenerated by the handoff pipeline",
        "does_not_prove": "external source review is complete",
    },
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--allow-dirty", action="store_true")
    args = parser.parse_args()

    repo_root = ROOT
    if not args.allow_dirty and _git_dirty(repo_root):
        print("v1 RC packet generation refused: working tree is dirty", file=sys.stderr)
        return 1

    output_dir = Path(args.output_dir)
    packet = build_packet(repo_root, output_dir)
    print(f"Built v1.0 RC packet at {packet['output_dir']}")
    return 0


def build_packet(repo_root: Path, output_dir: Path) -> dict[str, Any]:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    readiness = v1_rc_readiness_check.build_report(repo_root)
    commit = _git_commit(repo_root)
    files: list[Path] = []

    index_path = output_dir / "00_V1_RC_PACKET_INDEX.md"
    index_path.write_text(_index_markdown(commit, readiness), encoding="utf-8")
    files.append(index_path)

    for output_name, source in SOURCE_DOCS:
        destination = output_dir / output_name
        destination.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
        files.append(destination)

    artifacts_path = output_dir / "14_V1_RC_ARTIFACTS.md"
    artifacts_path.write_text(_artifacts_markdown(repo_root), encoding="utf-8")
    files.append(artifacts_path)

    commands_path = output_dir / "15_V1_RC_COMMANDS.md"
    commands_path.write_text(_commands_markdown(readiness), encoding="utf-8")
    files.append(commands_path)

    hashes = _artifact_hashes(output_dir, files)
    hashes_path = output_dir / "v1-rc-artifact-hashes.json"
    hashes_path.write_text(json.dumps(hashes, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    files.append(hashes_path)

    return {
        "output_dir": output_dir.as_posix(),
        "commit": commit,
        "artifact_count": len(files),
        "hashes": hashes,
    }


def _index_markdown(commit: str, readiness: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Ithildin v1.0 RC Packet",
            "",
            "Status: compact local-preview release-candidate handoff packet.",
            "",
            f"- Commit: `{commit}`",
            f"- Tool count: `{readiness['tool_count']}`",
            f"- Latest implemented tool: `{readiness['latest_implemented_tool']}`",
            f"- Selected capability: `{readiness['selected_capability']}`",
            f"- Pending external-review rows: `{readiness['pending_external_review_rows']}`",
            f"- Packet redaction findings: `{readiness['packet_redaction_findings']}`",
            "- Capability expansion: blocked",
            "- Public/security-product positioning: blocked",
            "",
            "## Reading Order",
            "",
            "1. `01_V1_RC_STATUS.md`",
            "2. `02_V1_OPERATOR_QUICKSTART.md`",
            "3. `02A_V1_OPERATOR_TRIAL_CHECKLIST.md`",
            "4. `03_V1_WORKBENCH_EVIDENCE_CLOSURE.md`",
            "5. `04_V1_ASSURANCE_CLOSURE.md`",
            "6. `05_V1_RC_FEATURE_FREEZE.md`",
            "7. `06_V1_RC_READINESS_GATE.md`",
            "8. `07_ENTERPRISE_READINESS_RUNWAY.md`",
            "9. `08_MISSION_CONTROL_DISPLAY_PROPOSAL.md`",
            "10. `09_MISSION_CONTROL_HANDOFF_SCHEMA.md`",
            "11. `10_MISSION_CONTROL_NEGATIVE_FIXTURES.md`",
            "12. `11_V1_RC_EXTERNAL_REVIEW_PROMPT.md`",
            "13. `12_V1_RC_FINAL_HANDOFF.md`",
            "14. `13_V1_RC_POST_REVIEW_TRIAGE.md`",
            "15. `14_V1_RC_ARTIFACTS.md`",
            "16. `15_V1_RC_COMMANDS.md`",
            "17. `v1-rc-artifact-hashes.json`",
            "",
            "This packet is local handoff evidence only. It is not production approval, external",
            "source-review closure, custody-grade audit, sandbox approval, SIEM approval, or",
            "compliance automation.",
            "",
        ]
    )


def _artifacts_markdown(repo_root: Path) -> str:
    rows = []
    for reference in ARTIFACT_REFERENCES:
        path = repo_root / reference["path"]
        digest = _path_digest(path) if path.exists() else "missing"
        rows.append(
            (
                "| `{path}` | `{exists}` | `{digest}` | {purpose} | {proves} | "
                "{does_not_prove} |"
            ).format(
                path=reference["path"],
                exists=str(path.exists()).lower(),
                digest=digest,
                purpose=reference["purpose"],
                proves=reference["proves"],
                does_not_prove=reference["does_not_prove"],
            )
        )
    return "\n".join(
        [
            "# v1.0 RC Artifact Map",
            "",
            "This map points reviewers and operators to the current ignored/generated evidence",
            "artifacts that support the v1.0 local-preview RC story. Hashes are",
            "handoff-integrity evidence only; they are not notarization, custody-grade audit,",
            "external review closure, or production",
            "approval.",
            "",
            "| Artifact | Exists | SHA-256 | Purpose | Proves | Does not prove |",
            "| --- | --- | --- | --- | --- | --- |",
            *rows,
            "",
            "The current packet may record sandbox promotion only as `not_promoted`. Any",
            "trusted-host promotion state beyond that requires a separate proposal,",
            "implementation gate, source review, negative transcripts, and release-readiness",
            "update.",
            "",
        ]
    )


def _commands_markdown(readiness: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# v1.0 RC Commands",
            "",
            "Run these from the Ithildin repo root:",
            "",
            "```sh",
            "make v1-rc-readiness",
            "make v1-rc-packet",
            "make release-check",
            "make review-candidate",
            "```",
            "",
            "## Latest Readiness Snapshot",
            "",
            "```json",
            json.dumps(readiness, indent=2, sort_keys=True),
            "```",
            "",
        ]
    )


def _path_digest(path: Path) -> str:
    digest = hashlib.sha256()
    if path.is_file():
        digest.update(path.read_bytes())
        return "sha256:" + digest.hexdigest()
    for child in sorted(p for p in path.rglob("*") if p.is_file()):
        digest.update(child.relative_to(path).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(child.read_bytes())
        digest.update(b"\0")
    return "sha256:" + digest.hexdigest()


def _artifact_hashes(output_dir: Path, files: list[Path]) -> dict[str, Any]:
    artifacts = []
    for path in files:
        if path.name == "v1-rc-artifact-hashes.json":
            continue
        content = path.read_bytes()
        artifacts.append(
            {
                "path": path.relative_to(output_dir).as_posix(),
                "sha256": "sha256:" + hashlib.sha256(content).hexdigest(),
                "bytes": len(content),
            }
        )
    return {"schema_version": "1", "artifacts": artifacts}


def _git_commit(repo_root: Path) -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo_root, text=True).strip()


def _git_dirty(repo_root: Path) -> bool:
    return bool(subprocess.check_output(["git", "status", "--short"], cwd=repo_root, text=True))


if __name__ == "__main__":
    raise SystemExit(main())
