"""Generate a secret-free operator workbench demo smoke transcript."""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import workbench_readiness

DEFAULT_OUTPUT = Path("var/review-packets/v3/operator-workbench/WORKBENCH_DEMO_SMOKE.md")
PROJECT_MARKERS = [
    Path("pyproject.toml"),
    Path("Makefile"),
    Path("apps/api"),
    Path("apps/mcp-server"),
    Path("tool-manifests.lock.json"),
]
OBSERVED_COMMANDS = [
    ["make", "workbench-readiness"],
    ["make", "live-demo-preflight"],
    ["make", "live-demo-status"],
    ["make", "live-demo-evidence-summary"],
    ["make", "operator-sandbox-demo-readiness"],
    ["make", "agent-run-operations-readiness"],
    ["make", "no-new-powers-guardrail"],
    ["make", "tool-surface-invariant-gate"],
]
OPERATOR_SEQUENCE = [
    ("Preflight", "make live-demo-preflight", "required before local demo setup"),
    ("Seed", "make demo-seed", "optional if the ignored demo workspace already exists"),
    ("Start local UI/API", "make compose-up && make compose-smoke", "optional Compose path"),
    ("MCP server", "uv run python -m ithildin_mcp_server", "manual local stdio client command"),
    ("Governed demo flow", "make demo-flow", "optional mutating demo-workspace flow"),
    ("Inspect dashboard", "open http://127.0.0.1:5173", "manual browser step"),
    ("Export run evidence", "Export Run Evidence", "manual review-console download"),
    ("Refresh evidence", "make demo-workbench", "read-only/ignored-output evidence wrapper"),
    ("Cleanup", "make compose-down", "optional if Compose was started"),
]


class WorkbenchDemoSmokeError(RuntimeError):
    """Raised when the workbench demo smoke transcript cannot be generated."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--skip-commands", action="store_true")
    args = parser.parse_args()
    try:
        path = build_transcript(
            repo_root=Path.cwd().resolve(),
            output=args.output,
            run_commands=not args.skip_commands,
        )
    except WorkbenchDemoSmokeError as exc:
        print(f"workbench demo smoke failed: {exc}", file=sys.stderr)
        return 1
    print(f"Built workbench demo smoke transcript at {path}")
    return 0


def build_transcript(*, repo_root: Path, output: Path, run_commands: bool = True) -> Path:
    _require_project_root(repo_root)
    readiness = workbench_readiness.build_report(repo_root)
    outputs = [
        _command_output(command, repo_root=repo_root, run_commands=run_commands)
        for command in OBSERVED_COMMANDS
    ]
    failures = [item for item in outputs if item["returncode"] != 0]
    if failures and run_commands:
        failed = ", ".join(" ".join(item["command"]) for item in failures)
        raise WorkbenchDemoSmokeError(f"observed command failed: {failed}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_render(readiness=readiness, outputs=outputs), encoding="utf-8")
    return output


def _render(*, readiness: dict[str, Any], outputs: list[dict[str, Any]]) -> str:
    lines = [
        "# Workbench Demo Smoke Transcript",
        "",
        "This transcript is generated by `make demo-workbench-smoke`. It is secret-free and",
        "does not start services, call governed tools, approve actions, repair diagnostics,",
        "or manage containers.",
        "",
        "## Status",
        "",
        f"- generated_at: `{datetime.now(UTC).isoformat()}`",
        f"- workbench_readiness_valid: `{str(readiness['valid']).lower()}`",
        f"- tool_count: `{readiness.get('tool_count')}`",
        "- new_power_classes_allowed: `false`",
        "- run_control_behavior_allowed: `false`",
        "- sandbox_orchestration_allowed: `false`",
        "",
        "## Operator Flow",
        "",
    ]
    for label, command, note in OPERATOR_SEQUENCE:
        lines.append(f"- {label}: `{command}` - {note}.")
    lines.extend(["", "## Observed Readiness Commands", ""])
    for output in outputs:
        lines.extend(
            [
                f"### {' '.join(output['command'])}",
                "",
                f"- exit code: `{output['returncode']}`",
                "",
                "```text",
                str(output["stdout"]).rstrip(),
                "```",
                "",
            ]
        )
        if output["stderr"]:
            lines.extend(["stderr:", "", "```text", str(output["stderr"]).rstrip(), "```", ""])
    lines.extend(
        [
            "## Boundary",
            "",
            "This smoke transcript does not prove OS isolation, production deployment safety,",
            "SIEM custody, compliance automation, host compromise resistance, or activity",
            "outside Ithildin-mediated actions.",
            "",
        ]
    )
    return "\n".join(lines)


def _require_project_root(repo_root: Path) -> None:
    missing = [path.as_posix() for path in PROJECT_MARKERS if not (repo_root / path).exists()]
    if missing:
        raise WorkbenchDemoSmokeError(
            f"must be run from Ithildin repo root; missing {', '.join(missing)}"
        )


def _command_output(
    command: list[str],
    *,
    repo_root: Path,
    run_commands: bool,
) -> dict[str, Any]:
    if not run_commands:
        return {
            "command": command,
            "returncode": 0,
            "stdout": "command execution skipped for fixture/test transcript generation",
            "stderr": "",
        }
    result = subprocess.run(command, cwd=repo_root, check=False, capture_output=True, text=True)
    return {
        "command": command,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


if __name__ == "__main__":
    raise SystemExit(main())
